/**
 * Default sample rooms extracted directly from Master Excel "Site Detail Sheet. R5.xls"
 * Used when a lead has not yet configured custom site detail sheet rooms.
 */
export const SAMPLE_SITE_DETAIL_ROOMS = [
  {
    "id": "room-1",
    "sheetName": "Living Room - W1",
    "roomTitle": "Living Room W1",
    "sheetNo": 1,
    "clientName": "Mr.Rakesh Jain",
    "architect": "ADID Atelier LLP.",
    "siteIncharge": "Esha / Arisha / Rucha / Namrata",
    "notes": [
      "Width of the Fabric as ht, of the Window",
      "Width of the Fabric as ht, of the Window"
    ],
    "items": [
      {
        "id": "item-1-2",
        "srNo": 2,
        "look": "",
        "type": "W1 Reverse Mock",
        "windowWidth": "55\"",
        "windowHeight": 113,
        "pelmetWidth": 12,
        "pelmetDrop": 6,
        "pelmetReturn": "",
        "catalogueImages": [],
        "design": "Ready with Trim",
        "brand": "Olake /",
        "fabricName": "H0692-17",
        "fabricWidth": "300",
        "repeatV": "",
        "repeatH": "",
        "fullness": 3,
        "qtyMtrs": 5,
        "stitchingStyle": "Knife",
        "parts": 1.5,
        "opening": "Lock on Left",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "in house 301 blackout",
        "liningQty": "",
        "tieback": "",
        "position": "1",
        "electricalPoint": "",
        "installationType": ""
      },
      {
        "id": "item-1-1",
        "srNo": 1,
        "look": "",
        "type": "W1 Drape Mock",
        "windowWidth": "40\"",
        "windowHeight": 113,
        "pelmetWidth": "",
        "pelmetDrop": "",
        "pelmetReturn": "",
        "catalogueImages": [],
        "design": "Ready",
        "brand": "D Décor Aura / \nGlorious",
        "fabricName": "Sr.No. 125 / \nQuality : Nampa - New / \nDesign : Plain / \nShade : 429",
        "fabricWidth": "140",
        "repeatV": "",
        "repeatH": "",
        "fullness": 3,
        "qtyMtrs": 11,
        "stitchingStyle": "Knife",
        "parts": 3,
        "opening": "Lock on Left",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "",
        "liningQty": "",
        "tieback": "",
        "position": "2",
        "electricalPoint": "",
        "installationType": ""
      },
      {
        "id": "item-1-3",
        "srNo": 3,
        "look": "",
        "type": "Trim",
        "windowWidth": "",
        "windowHeight": "",
        "pelmetWidth": "",
        "pelmetDrop": "",
        "pelmetReturn": "",
        "catalogueImages": [],
        "design": "Order by ishani M",
        "brand": "",
        "fabricName": "",
        "fabricWidth": "",
        "repeatV": "",
        "repeatH": "",
        "fullness": "",
        "qtyMtrs": "",
        "stitchingStyle": "",
        "parts": "",
        "opening": "",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "",
        "liningQty": "",
        "tieback": "",
        "position": "",
        "electricalPoint": "",
        "installationType": ""
      },
      {
        "id": "item-1-4",
        "srNo": 4,
        "look": "",
        "type": "Tessels",
        "windowWidth": "",
        "windowHeight": "",
        "pelmetWidth": "",
        "pelmetDrop": "",
        "pelmetReturn": "",
        "catalogueImages": [],
        "design": "Ready",
        "brand": "IKN \nIKON Accessories 2022",
        "fabricName": "544104",
        "fabricWidth": "",
        "repeatV": "",
        "repeatH": "",
        "fullness": "",
        "qtyMtrs": "1 - Pc",
        "stitchingStyle": "",
        "parts": "",
        "opening": "",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "",
        "liningQty": "",
        "tieback": "",
        "position": "",
        "electricalPoint": "",
        "installationType": ""
      },
      {
        "id": "item-1-5",
        "srNo": 5,
        "look": "",
        "type": "Knobs",
        "windowWidth": "",
        "windowHeight": "",
        "pelmetWidth": "",
        "pelmetDrop": "",
        "pelmetReturn": "",
        "catalogueImages": [],
        "design": "Ready",
        "brand": "IKN \nIKON Accessories 2022",
        "fabricName": "584103",
        "fabricWidth": "",
        "repeatV": "",
        "repeatH": "",
        "fullness": "",
        "qtyMtrs": "1 - Pc",
        "stitchingStyle": "",
        "parts": "",
        "opening": "",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "",
        "liningQty": "",
        "tieback": "",
        "position": "",
        "electricalPoint": "",
        "installationType": ""
      },
      {
        "id": "item-1-6",
        "srNo": 6,
        "look": "",
        "type": "W1 Sheer Curtain",
        "windowWidth": 253,
        "windowHeight": 113,
        "pelmetWidth": "",
        "pelmetDrop": "",
        "pelmetReturn": "",
        "catalogueImages": [],
        "design": "Ready with Fringes",
        "brand": "Lihuamingxiu",
        "fabricName": "H104 - 1",
        "fabricWidth": "280",
        "repeatV": "",
        "repeatH": "",
        "fullness": 2.5,
        "qtyMtrs": 17,
        "stitchingStyle": "Ripple",
        "parts": "",
        "opening": "",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "",
        "liningQty": "",
        "tieback": "",
        "position": "3",
        "electricalPoint": "",
        "installationType": ""
      },
      {
        "id": "item-1-7",
        "srNo": 7,
        "look": "",
        "type": "Fringes 20\"",
        "windowWidth": "",
        "windowHeight": "",
        "pelmetWidth": "",
        "pelmetDrop": "",
        "pelmetReturn": "",
        "catalogueImages": [],
        "design": "Order by ishani M",
        "brand": "",
        "fabricName": "",
        "fabricWidth": "",
        "repeatV": "",
        "repeatH": "",
        "fullness": "",
        "qtyMtrs": "",
        "stitchingStyle": "",
        "parts": "",
        "opening": "",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "",
        "liningQty": "",
        "tieback": "",
        "position": "",
        "electricalPoint": "",
        "installationType": ""
      },
      {
        "id": "item-1-8",
        "srNo": 8,
        "look": "",
        "type": "Fringess Back Fabric",
        "windowWidth": "",
        "windowHeight": "",
        "pelmetWidth": "",
        "pelmetDrop": "",
        "pelmetReturn": "",
        "catalogueImages": [],
        "design": "In house Net Fabric",
        "brand": "White Net \nM-00",
        "fabricName": "",
        "fabricWidth": "54\"",
        "repeatV": "",
        "repeatH": "",
        "fullness": "",
        "qtyMtrs": 8.5,
        "stitchingStyle": "",
        "parts": "",
        "opening": "",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "",
        "liningQty": "",
        "tieback": "",
        "position": "",
        "electricalPoint": "",
        "installationType": ""
      }
    ]
  },
  {
    "id": "room-2",
    "sheetName": "Living Room - W2",
    "roomTitle": "Living Room W2",
    "sheetNo": 2,
    "clientName": "Mr.Rakesh Jain",
    "architect": "ADID Atelier LLP.",
    "siteIncharge": "Esha / Arisha / Rucha / Namrata",
    "notes": [
      "Width of the Fabric as ht, of the Window",
      "Width of the Fabric as ht, of the Window"
    ],
    "items": [
      {
        "id": "item-2-1",
        "srNo": 1,
        "look": "",
        "type": "W2 Reverse Mock",
        "windowWidth": "52\"",
        "windowHeight": 113,
        "pelmetWidth": 12,
        "pelmetDrop": 6,
        "pelmetReturn": "",
        "catalogueImages": [],
        "design": "Ready with Trim",
        "brand": "Olake /",
        "fabricName": "H0692-17",
        "fabricWidth": "300",
        "repeatV": "",
        "repeatH": "",
        "fullness": 3,
        "qtyMtrs": 5,
        "stitchingStyle": "Knife",
        "parts": 1.5,
        "opening": "",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "in house 301 blackout",
        "liningQty": "",
        "tieback": "",
        "position": "1",
        "electricalPoint": "",
        "installationType": ""
      },
      {
        "id": "item-2-2",
        "srNo": 2,
        "look": "",
        "type": "W2 Drape Mock",
        "windowWidth": "40\"",
        "windowHeight": 113,
        "pelmetWidth": "",
        "pelmetDrop": "",
        "pelmetReturn": "",
        "catalogueImages": [],
        "design": "Ready",
        "brand": "D Décor Aura / \nGlorious",
        "fabricName": "Sr.No. 125 / \nQuality : Nampa - New / \nDesign : Plain / \nShade : 429",
        "fabricWidth": "140",
        "repeatV": "",
        "repeatH": "",
        "fullness": 3,
        "qtyMtrs": 11,
        "stitchingStyle": "Knife",
        "parts": 3,
        "opening": "",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "",
        "liningQty": "",
        "tieback": "",
        "position": "2",
        "electricalPoint": "",
        "installationType": ""
      },
      {
        "id": "item-2-3",
        "srNo": 3,
        "look": "",
        "type": "Trim",
        "windowWidth": "",
        "windowHeight": "",
        "pelmetWidth": "",
        "pelmetDrop": "",
        "pelmetReturn": "",
        "catalogueImages": [],
        "design": "Order by ishani M",
        "brand": "",
        "fabricName": "",
        "fabricWidth": "",
        "repeatV": "",
        "repeatH": "",
        "fullness": "",
        "qtyMtrs": "",
        "stitchingStyle": "",
        "parts": "",
        "opening": "",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "",
        "liningQty": "",
        "tieback": "",
        "position": "",
        "electricalPoint": "",
        "installationType": ""
      },
      {
        "id": "item-2-4",
        "srNo": 4,
        "look": "",
        "type": "Tessels",
        "windowWidth": "",
        "windowHeight": "",
        "pelmetWidth": "",
        "pelmetDrop": "",
        "pelmetReturn": "",
        "catalogueImages": [],
        "design": "Ready",
        "brand": "IKN \nIKON Accessories 2022",
        "fabricName": "544104",
        "fabricWidth": "",
        "repeatV": "",
        "repeatH": "",
        "fullness": "",
        "qtyMtrs": "1 - Pc",
        "stitchingStyle": "",
        "parts": "",
        "opening": "",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "",
        "liningQty": "",
        "tieback": "",
        "position": "",
        "electricalPoint": "",
        "installationType": ""
      },
      {
        "id": "item-2-5",
        "srNo": 5,
        "look": "",
        "type": "Knobs",
        "windowWidth": "",
        "windowHeight": "",
        "pelmetWidth": "",
        "pelmetDrop": "",
        "pelmetReturn": "",
        "catalogueImages": [],
        "design": "Ready",
        "brand": "IKN \nIKON Accessories 2022",
        "fabricName": "584103",
        "fabricWidth": "",
        "repeatV": "",
        "repeatH": "",
        "fullness": "",
        "qtyMtrs": "1 - Pc",
        "stitchingStyle": "",
        "parts": "",
        "opening": "",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "",
        "liningQty": "",
        "tieback": "",
        "position": "",
        "electricalPoint": "",
        "installationType": ""
      },
      {
        "id": "item-2-6",
        "srNo": 6,
        "look": "",
        "type": "W2 Sheer Curtain",
        "windowWidth": 52.75,
        "windowHeight": 113,
        "pelmetWidth": "",
        "pelmetDrop": "",
        "pelmetReturn": "",
        "catalogueImages": [],
        "design": "Ready with Fringes",
        "brand": "Lihuamingxiu",
        "fabricName": "H104 - 1",
        "fabricWidth": "280",
        "repeatV": "",
        "repeatH": "",
        "fullness": 2.5,
        "qtyMtrs": 4,
        "stitchingStyle": "Ripple",
        "parts": "",
        "opening": "",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "",
        "liningQty": "",
        "tieback": "",
        "position": "",
        "electricalPoint": "",
        "installationType": ""
      },
      {
        "id": "item-2-7",
        "srNo": 7,
        "look": "",
        "type": "Fringes 20\"",
        "windowWidth": "",
        "windowHeight": "",
        "pelmetWidth": "",
        "pelmetDrop": "",
        "pelmetReturn": "",
        "catalogueImages": [],
        "design": "Order by ishani M",
        "brand": "",
        "fabricName": "",
        "fabricWidth": "",
        "repeatV": "",
        "repeatH": "",
        "fullness": "",
        "qtyMtrs": "",
        "stitchingStyle": "",
        "parts": "",
        "opening": "",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "",
        "liningQty": "",
        "tieback": "",
        "position": "",
        "electricalPoint": "",
        "installationType": ""
      },
      {
        "id": "item-2-8",
        "srNo": 8,
        "look": "",
        "type": "Fringess Back Fabric",
        "windowWidth": "",
        "windowHeight": "",
        "pelmetWidth": "",
        "pelmetDrop": "",
        "pelmetReturn": "",
        "catalogueImages": [],
        "design": "In house Net Fabric",
        "brand": "White Net \nM-00",
        "fabricName": "",
        "fabricWidth": "54\"",
        "repeatV": "",
        "repeatH": "",
        "fullness": "",
        "qtyMtrs": 4,
        "stitchingStyle": "",
        "parts": "",
        "opening": "",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "",
        "liningQty": "",
        "tieback": "",
        "position": "",
        "electricalPoint": "",
        "installationType": ""
      }
    ]
  },
  {
    "id": "room-3",
    "sheetName": "Living Room - W3",
    "roomTitle": "Living Room W3",
    "sheetNo": 3,
    "clientName": "Mr.Rakesh Jain",
    "architect": "ADID Atelier LLP.",
    "siteIncharge": "Esha / Arisha / Rucha / Namrata",
    "notes": [
      "Width of the Fabric as ht, of the Window",
      "Width of the Fabric as ht, of the Window"
    ],
    "items": [
      {
        "id": "item-3-1",
        "srNo": 1,
        "look": "",
        "type": "W3 Reverse Mock",
        "windowWidth": "55\" + 55\"",
        "windowHeight": 113,
        "pelmetWidth": 12,
        "pelmetDrop": 6,
        "pelmetReturn": "",
        "catalogueImages": [],
        "design": "Ready with Trim",
        "brand": "Olake /",
        "fabricName": "H0692-17",
        "fabricWidth": "300",
        "repeatV": "",
        "repeatH": "",
        "fullness": 3,
        "qtyMtrs": 10,
        "stitchingStyle": "Knife",
        "parts": "1.5 + 1.5",
        "opening": "",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "in house 301 blackout",
        "liningQty": "",
        "tieback": "",
        "position": "1",
        "electricalPoint": "",
        "installationType": ""
      },
      {
        "id": "item-3-2",
        "srNo": 2,
        "look": "",
        "type": "W3 Drape Mock",
        "windowWidth": "40\" + 40\"",
        "windowHeight": 113,
        "pelmetWidth": "",
        "pelmetDrop": "",
        "pelmetReturn": "",
        "catalogueImages": [],
        "design": "Ready",
        "brand": "D Décor Aura / \nGlorious",
        "fabricName": "Sr.No. 125 / \nQuality : Nampa - New / \nDesign : Plain / \nShade : 429",
        "fabricWidth": "140",
        "repeatV": "",
        "repeatH": "",
        "fullness": 3,
        "qtyMtrs": 21.5,
        "stitchingStyle": "Knife",
        "parts": "3+3",
        "opening": "",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "",
        "liningQty": "",
        "tieback": "",
        "position": "2",
        "electricalPoint": "",
        "installationType": ""
      },
      {
        "id": "item-3-3",
        "srNo": 3,
        "look": "",
        "type": "Trim",
        "windowWidth": "",
        "windowHeight": "",
        "pelmetWidth": "",
        "pelmetDrop": "",
        "pelmetReturn": "",
        "catalogueImages": [],
        "design": "Order by ishani M",
        "brand": "",
        "fabricName": "",
        "fabricWidth": "",
        "repeatV": "",
        "repeatH": "",
        "fullness": "",
        "qtyMtrs": "",
        "stitchingStyle": "",
        "parts": "",
        "opening": "",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "",
        "liningQty": "",
        "tieback": "",
        "position": "",
        "electricalPoint": "",
        "installationType": ""
      },
      {
        "id": "item-3-4",
        "srNo": 4,
        "look": "",
        "type": "Tessels",
        "windowWidth": "",
        "windowHeight": "",
        "pelmetWidth": "",
        "pelmetDrop": "",
        "pelmetReturn": "",
        "catalogueImages": [],
        "design": "Ready",
        "brand": "IKN \nIKON Accessories 2022",
        "fabricName": "544104",
        "fabricWidth": "",
        "repeatV": "",
        "repeatH": "",
        "fullness": "",
        "qtyMtrs": "2 - Pc",
        "stitchingStyle": "",
        "parts": "",
        "opening": "",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "",
        "liningQty": "",
        "tieback": "",
        "position": "",
        "electricalPoint": "",
        "installationType": ""
      },
      {
        "id": "item-3-5",
        "srNo": 5,
        "look": "",
        "type": "Knobs",
        "windowWidth": "",
        "windowHeight": "",
        "pelmetWidth": "",
        "pelmetDrop": "",
        "pelmetReturn": "",
        "catalogueImages": [],
        "design": "Ready",
        "brand": "IKN \nIKON Accessories 2022",
        "fabricName": "584103",
        "fabricWidth": "",
        "repeatV": "",
        "repeatH": "",
        "fullness": "",
        "qtyMtrs": "2 - Pc",
        "stitchingStyle": "",
        "parts": "",
        "opening": "",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "",
        "liningQty": "",
        "tieback": "",
        "position": "",
        "electricalPoint": "",
        "installationType": ""
      },
      {
        "id": "item-3-6",
        "srNo": 6,
        "look": "",
        "type": "W3 Sheer Curtain",
        "windowWidth": 224,
        "windowHeight": 113,
        "pelmetWidth": "",
        "pelmetDrop": "",
        "pelmetReturn": "",
        "catalogueImages": [],
        "design": "Ready with Fringes",
        "brand": "Lihuamingxiu",
        "fabricName": "H104 - 1",
        "fabricWidth": "280",
        "repeatV": "",
        "repeatH": "",
        "fullness": 2.5,
        "qtyMtrs": 15.5,
        "stitchingStyle": "Ripple",
        "parts": "",
        "opening": "",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "",
        "liningQty": "",
        "tieback": "",
        "position": "",
        "electricalPoint": "",
        "installationType": ""
      },
      {
        "id": "item-3-7",
        "srNo": 7,
        "look": "",
        "type": "Fringes 20\"",
        "windowWidth": "",
        "windowHeight": "",
        "pelmetWidth": "",
        "pelmetDrop": "",
        "pelmetReturn": "",
        "catalogueImages": [],
        "design": "Order by ishani M",
        "brand": "",
        "fabricName": "",
        "fabricWidth": "",
        "repeatV": "",
        "repeatH": "",
        "fullness": "",
        "qtyMtrs": "",
        "stitchingStyle": "",
        "parts": "",
        "opening": "",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "",
        "liningQty": "",
        "tieback": "",
        "position": "",
        "electricalPoint": "",
        "installationType": ""
      },
      {
        "id": "item-3-8",
        "srNo": 8,
        "look": "",
        "type": "Fringess Back Fabric",
        "windowWidth": "",
        "windowHeight": "",
        "pelmetWidth": "",
        "pelmetDrop": "",
        "pelmetReturn": "",
        "catalogueImages": [],
        "design": "In house Net Fabric",
        "brand": "White Net \nM-00",
        "fabricName": "",
        "fabricWidth": "54\"",
        "repeatV": "",
        "repeatH": "",
        "fullness": "",
        "qtyMtrs": 8,
        "stitchingStyle": "",
        "parts": "",
        "opening": "",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "",
        "liningQty": "",
        "tieback": "",
        "position": "",
        "electricalPoint": "",
        "installationType": ""
      }
    ]
  },
  {
    "id": "room-4",
    "sheetName": "Mandir Area",
    "roomTitle": "Mandir Area",
    "sheetNo": 4,
    "clientName": "Mr.Rakesh Jain",
    "architect": "ADID Atelier LLP.",
    "siteIncharge": "Esha / Arisha / Rucha / Namrata",
    "notes": [
      "Width of the Fabric as height of the Window (Vertical Lines Want) adjust in stitching"
    ],
    "items": [
      {
        "id": "item-4-1",
        "srNo": 1,
        "look": "",
        "type": "Roller Blind",
        "windowWidth": "",
        "windowHeight": "",
        "pelmetWidth": "",
        "pelmetDrop": "",
        "pelmetReturn": "",
        "catalogueImages": [],
        "design": "",
        "brand": "",
        "fabricName": "",
        "fabricWidth": "",
        "repeatV": "",
        "repeatH": "",
        "fullness": "",
        "qtyMtrs": "",
        "stitchingStyle": "",
        "parts": "",
        "opening": "",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "",
        "liningQty": "",
        "tieback": "",
        "position": "",
        "electricalPoint": "",
        "installationType": ""
      }
    ]
  },
  {
    "id": "room-5",
    "sheetName": "Guest Room",
    "roomTitle": "Guest Room",
    "sheetNo": 5,
    "clientName": "Mr.Rakesh Jain",
    "architect": "ADID Atelier LLP.",
    "siteIncharge": "Esha / Arisha / Rucha / Namrata",
    "notes": [
      "Width of the Fabric as height of the Window (Vertical Lines Want) adjust in stitching"
    ],
    "items": [
      {
        "id": "item-5-1",
        "srNo": 1,
        "look": "",
        "type": "Main Curtain",
        "windowWidth": 124,
        "windowHeight": 113,
        "pelmetWidth": 12,
        "pelmetDrop": 6,
        "pelmetReturn": "",
        "catalogueImages": [
          "/site-sheets/guest-room/img_0.jpg",
          "/site-sheets/guest-room/img_1.jpg"
        ],
        "design": "Ready",
        "brand": "Deco Dome / \nLinia /",
        "fabricName": "Linia One / \nAlora - 1",
        "fabricWidth": "54\"",
        "repeatV": "",
        "repeatH": "",
        "fullness": 2.5,
        "qtyMtrs": 22.5,
        "stitchingStyle": "Ripple",
        "parts": 7,
        "opening": "Center Open",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "in house 301 blackout",
        "liningQty": "",
        "tieback": "Custom",
        "position": "",
        "electricalPoint": "",
        "installationType": ""
      },
      {
        "id": "item-5-2",
        "srNo": 2,
        "look": "",
        "type": "Sheer Curtain",
        "windowWidth": 124,
        "windowHeight": 113,
        "pelmetWidth": "",
        "pelmetDrop": "",
        "pelmetReturn": "",
        "catalogueImages": [
          "/site-sheets/guest-room/img_2.jpg",
          "/site-sheets/guest-room/img_3.jpg",
          "/site-sheets/guest-room/img_4.jpg",
          "/site-sheets/guest-room/img_5.jpg"
        ],
        "design": "Ready",
        "brand": "Fabri Care /\nLineal 2/2",
        "fabricName": "Lineal / \nSr.No. 05 / \nQuality : Concord / \nDesign : Course / \nShade : Ratten",
        "fabricWidth": "300",
        "repeatV": "",
        "repeatH": "",
        "fullness": 2.5,
        "qtyMtrs": 9,
        "stitchingStyle": "Ripple",
        "parts": "",
        "opening": "Center Open",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "",
        "liningQty": "",
        "tieback": "Reg",
        "position": "",
        "electricalPoint": "",
        "installationType": ""
      }
    ]
  },
  {
    "id": "room-6",
    "sheetName": "Rakesh & Sangita Room",
    "roomTitle": "Rakesh & Sangita Room",
    "sheetNo": 6,
    "clientName": "Mr.Rakesh Jain",
    "architect": "ADID Atelier LLP.",
    "siteIncharge": "Esha / Arisha / Rucha / Namrata",
    "notes": [
      "Design File Will Share by ishani M and Akansha"
    ],
    "items": [
      {
        "id": "item-6-1",
        "srNo": 1,
        "look": "",
        "type": "Main Curtain",
        "windowWidth": 116.2,
        "windowHeight": 113,
        "pelmetWidth": 12,
        "pelmetDrop": 6,
        "pelmetReturn": "",
        "catalogueImages": [],
        "design": "Ready",
        "brand": "Sansaar / \nCarlton",
        "fabricName": "Sr.No. 8 / \nPrice Code : D / \nDesign : Helena / \nColour : Manilla /",
        "fabricWidth": "140",
        "repeatV": "",
        "repeatH": "",
        "fullness": 2.5,
        "qtyMtrs": 19.5,
        "stitchingStyle": "Ripple",
        "parts": 6,
        "opening": "Lock on Left",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "in house 301 blackout",
        "liningQty": "",
        "tieback": "Custom",
        "position": "1",
        "electricalPoint": "",
        "installationType": ""
      },
      {
        "id": "item-6-2",
        "srNo": 2,
        "look": "",
        "type": "Sheer Curtain",
        "windowWidth": 116.2,
        "windowHeight": 113,
        "pelmetWidth": "",
        "pelmetDrop": "",
        "pelmetReturn": "",
        "catalogueImages": [],
        "design": "Custom - \nFrench Knot diagonal",
        "brand": "D Décor / \nSophia",
        "fabricName": "Sophia / \nSr.No. 9 / \nPrice Code : A / \nQuality : PC Linen SRD 7468DP / \nDesign :  Plain / \nShade : 58752 /",
        "fabricWidth": "140",
        "repeatV": "",
        "repeatH": "",
        "fullness": 2.5,
        "qtyMtrs": 19.5,
        "stitchingStyle": "Ripple",
        "parts": 6,
        "opening": "Lock on Left",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "",
        "liningQty": "",
        "tieback": "",
        "position": "2",
        "electricalPoint": "",
        "installationType": ""
      }
    ]
  },
  {
    "id": "room-7",
    "sheetName": "Rishabh and Priyal Room",
    "roomTitle": "Rishabh and Priyal Room",
    "sheetNo": 7,
    "clientName": "Mr.Rakesh Jain",
    "architect": "ADID Atelier LLP.",
    "siteIncharge": "Esha / Arisha / Rucha / Namrata",
    "notes": [
      "Width of the Fabric as ht of the Window",
      "Width of the Fabric as ht, of the Window (Once the Fabric arrives, pls inform me of its width. Based on that, we will decide the fall and band."
    ],
    "items": [
      {
        "id": "item-7-1",
        "srNo": 1,
        "look": "",
        "type": "Main Curtain",
        "windowWidth": 144.2,
        "windowHeight": 113,
        "pelmetWidth": 12,
        "pelmetDrop": 6,
        "pelmetReturn": "",
        "catalogueImages": [],
        "design": "Ready",
        "brand": "Le Dimora / \nChaster",
        "fabricName": "Pg No: 21 / \nCHAS 207-05 /",
        "fabricWidth": "290",
        "repeatV": "",
        "repeatH": "",
        "fullness": 2.5,
        "qtyMtrs": 10,
        "stitchingStyle": "Ripple",
        "parts": "1+1",
        "opening": "Center Open",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "in house 301 blackout",
        "liningQty": "",
        "tieback": "Custom",
        "position": "1",
        "electricalPoint": "",
        "installationType": ""
      },
      {
        "id": "item-7-2",
        "srNo": 2,
        "look": "",
        "type": "Sheer Curtain",
        "windowWidth": 144.2,
        "windowHeight": 113,
        "pelmetWidth": "",
        "pelmetDrop": "",
        "pelmetReturn": "",
        "catalogueImages": [],
        "design": "Ready",
        "brand": "Hanger No: 13 /",
        "fabricName": "SKU / \nEMB -129",
        "fabricWidth": "300",
        "repeatV": "",
        "repeatH": "",
        "fullness": 2.5,
        "qtyMtrs": 10,
        "stitchingStyle": "Ripple",
        "parts": "1+1",
        "opening": "Center Open",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "",
        "liningQty": "",
        "tieback": "Reg",
        "position": "2",
        "electricalPoint": "",
        "installationType": ""
      }
    ]
  },
  {
    "id": "room-8",
    "sheetName": "Kitchen",
    "roomTitle": "Kitchen",
    "sheetNo": 8,
    "clientName": "Mr.Rakesh Jain",
    "architect": "ADID Atelier LLP.",
    "siteIncharge": "Esha / Arisha / Rucha / Namrata",
    "notes": [
      "Width of the Fabric as height of the Window (Vertical Lines Want) adjust in stitching"
    ],
    "items": [
      {
        "id": "item-8-1",
        "srNo": 1,
        "look": "",
        "type": "Roller Blind",
        "windowWidth": "",
        "windowHeight": "",
        "pelmetWidth": "",
        "pelmetDrop": "",
        "pelmetReturn": "",
        "catalogueImages": [],
        "design": "",
        "brand": "",
        "fabricName": "",
        "fabricWidth": "",
        "repeatV": "",
        "repeatH": "",
        "fullness": "",
        "qtyMtrs": "",
        "stitchingStyle": "",
        "parts": "",
        "opening": "",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "",
        "liningQty": "",
        "tieback": "",
        "position": "",
        "electricalPoint": "",
        "installationType": ""
      }
    ]
  },
  {
    "id": "room-9",
    "sheetName": "Avik Room",
    "roomTitle": "Avik Room",
    "sheetNo": 9,
    "clientName": "Mr.Rakesh Jain",
    "architect": "ADID Atelier LLP.",
    "siteIncharge": "Esha / Arisha / Rucha / Namrata",
    "notes": [
      "Design File Will Share by ishani M"
    ],
    "items": [
      {
        "id": "item-9-1",
        "srNo": 1,
        "look": "",
        "type": "LW1+2 Main Curtain \n\n(Top Fabric)",
        "windowWidth": 213.1,
        "windowHeight": 113,
        "pelmetWidth": 12,
        "pelmetDrop": 6,
        "pelmetReturn": "",
        "catalogueImages": [],
        "design": "Ready \n\nTop Fabric \n79.1\"",
        "brand": "Sansaar / \nFables",
        "fabricName": "Sr.No. 37 / \nPrice Code : D / \nQuality : SRD 55876P / \nShade : 67582/",
        "fabricWidth": "140",
        "repeatV": "",
        "repeatH": "",
        "fullness": 2.5,
        "qtyMtrs": 23.5,
        "stitchingStyle": "Ripple",
        "parts": "5.5 + 5.5",
        "opening": "Center Open",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "In house 301 blackout",
        "liningQty": "",
        "tieback": "Custom",
        "position": "1",
        "electricalPoint": "",
        "installationType": ""
      },
      {
        "id": "item-9-2",
        "srNo": 2,
        "look": "",
        "type": "LW1+2 Sheer Curtain",
        "windowWidth": 213.1,
        "windowHeight": 113,
        "pelmetWidth": "",
        "pelmetDrop": "",
        "pelmetReturn": "",
        "catalogueImages": [],
        "design": "Ready",
        "brand": "Sansaar / \nFables",
        "fabricName": "Sr.No. 42 / \nPrice Code : B / \nQuality : Sheer SA 17751Y. Dull Thread Oriana / \nDesign : 377719 / \nShade : 45344 /",
        "fabricWidth": "140",
        "repeatV": "",
        "repeatH": "",
        "fullness": 2.5,
        "qtyMtrs": 35.5,
        "stitchingStyle": "Ripple",
        "parts": "5.5 + 5.5",
        "opening": "Center Open",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "",
        "liningQty": "",
        "tieback": "Reg",
        "position": "2",
        "electricalPoint": "",
        "installationType": ""
      }
    ]
  },
  {
    "id": "room-10",
    "sheetName": "Future Kids Room",
    "roomTitle": "Future Kids Room",
    "sheetNo": 10,
    "clientName": "Mr.Rakesh Jain",
    "architect": "ADID Atelier LLP.",
    "siteIncharge": "Esha / Arisha / Rucha / Namrata",
    "notes": [
      "Vertical Lines Want"
    ],
    "items": [
      {
        "id": "item-10-1",
        "srNo": 1,
        "look": "",
        "type": "Main Curtain",
        "windowWidth": 135.1,
        "windowHeight": 113,
        "pelmetWidth": 12,
        "pelmetDrop": 6,
        "pelmetReturn": "",
        "catalogueImages": [],
        "design": "Ready",
        "brand": "Pure ap Royale",
        "fabricName": "Velencia /\n 120763 /",
        "fabricWidth": "141",
        "repeatV": "",
        "repeatH": "",
        "fullness": 2.5,
        "qtyMtrs": 23,
        "stitchingStyle": "Ripple",
        "parts": "3.5 + 3.5",
        "opening": "Center Open",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "",
        "liningQty": "",
        "tieback": "",
        "position": "",
        "electricalPoint": "",
        "installationType": ""
      },
      {
        "id": "item-10-2",
        "srNo": 2,
        "look": "",
        "type": "Sheer Curtain",
        "windowWidth": 135.1,
        "windowHeight": 113,
        "pelmetWidth": "",
        "pelmetDrop": "",
        "pelmetReturn": "",
        "catalogueImages": [],
        "design": "Ready",
        "brand": "Deco Dome / \nLinia",
        "fabricName": "Linia - One / \nZoid  - 26",
        "fabricWidth": "54\"",
        "repeatV": "",
        "repeatH": "",
        "fullness": 2.5,
        "qtyMtrs": 23,
        "stitchingStyle": "Ripple",
        "parts": "3.5 + 3.5",
        "opening": "Center Open",
        "readyWidth": "",
        "readyHeight": "",
        "liningType": "",
        "liningQty": "",
        "tieback": "",
        "position": "",
        "electricalPoint": "",
        "installationType": ""
      }
    ]
  }
];
