/**
 * Fallback seed data for all 20 approved PMS stages.
 * Ensures that if the backend endpoint is not yet seeded or is temporarily unavailable,
 * the UI renders rich, interactive, realistic data populated with every client-approved field.
 */

export const PMS_STAGE_DEFAULTS = {
  projectActivation: [
    {
      id: 'pa-1',
      _id: 'pa-1',
      code: 'PRJ-101 (Villa Vista)',
      approvedQuote: '₹4,50,000',
      paymentReceipt: 'RCP-2026-081',
      projectActivationDate: '2026-09-15',
      clientApproval: 'Approved',
      assignedPcExecutionOwner: 'Vikram Mehta',
      kycBillingStatus: 'Verified',
      siteDetails: 'Villa 14, Palm Avenue, Sector 54, Gurgaon',
      status: 'Completed',
      createdAt: '2026-09-15T10:00:00.000Z',
    },
    {
      id: 'pa-2',
      _id: 'pa-2',
      code: 'PRJ-102 (Skyline Penthouse)',
      approvedQuote: '₹8,20,000',
      paymentReceipt: 'RCP-2026-092',
      projectActivationDate: '2026-09-20',
      clientApproval: 'Approved',
      assignedPcExecutionOwner: 'Ananya Sharma',
      kycBillingStatus: 'Verified',
      siteDetails: 'Penthouse B-3401, The Camellias, Golf Course Road',
      status: 'In Progress',
      createdAt: '2026-09-20T11:30:00.000Z',
    },
    {
      id: 'pa-3',
      _id: 'pa-3',
      code: 'PRJ-103 (Emerald Oasis)',
      approvedQuote: '₹3,10,000',
      paymentReceipt: 'RCP-2026-104',
      projectActivationDate: '2026-09-24',
      clientApproval: 'Pending',
      assignedPcExecutionOwner: 'Rhea Sen',
      kycBillingStatus: 'Pending',
      siteDetails: 'Plot 45, DLF Phase 1, Gurgaon',
      status: 'Pending',
      createdAt: '2026-09-24T09:15:00.000Z',
    },
  ],

  executionSetup: [
    {
      id: 'es-1',
      _id: 'es-1',
      code: 'PRJ-101 (Villa Vista)',
      dueDate: '2026-09-18',
      approvedDesign: 'v1.2 Approved',
      approvedQuote: '₹4,50,000',
      clientContext: 'Double height motorized curtains with blackout backing',
      paymentStatus: 'Complete',
      openActions: 'Power points verified by site electrician',
      executionOwnerPc: 'Vikram Mehta',
      siteDetails: 'Villa 14, Palm Avenue, Sector 54, Gurgaon',
      openRisks: 'Ceiling height requires special scaffolding',
      currentOwner: 'Vikram Mehta',
      status: 'Completed',
      delay: 'No',
      createdAt: '2026-09-16T10:00:00.000Z',
    },
    {
      id: 'es-2',
      _id: 'es-2',
      code: 'PRJ-102 (Skyline Penthouse)',
      dueDate: '2026-09-25',
      approvedDesign: 'v1.0 In Review',
      approvedQuote: '₹8,20,000',
      clientContext: 'Sheer curtains for all 6 bay windows with smart home integration',
      paymentStatus: 'Partial',
      openActions: 'Smart automation gateway specs needed from AV consultant',
      executionOwnerPc: 'Ananya Sharma',
      siteDetails: 'Penthouse B-3401, The Camellias',
      openRisks: 'Pending wall paint curing in master suite',
      currentOwner: 'Ananya Sharma',
      status: 'In Progress',
      delay: 'No',
      createdAt: '2026-09-21T14:00:00.000Z',
    },
  ],

  designFinalisation: [
    {
      id: 'df-1',
      _id: 'df-1',
      code: 'PRJ-101 (Villa Vista)',
      dueDate: '2026-09-20',
      finalDesignStatus: 'Approved',
      designVersion: 'v2.0',
      designApprovalDate: '2026-09-19',
      pendingDesignDecisions: 'Pelmet depth confirmed at 160mm',
      clientBrief: 'Living Room: Wave sheer + Silk blackout drapes',
      approvedProposalQuote: 'Q-2026-104 (₹4,50,000)',
      fabrics: 'Belgian Linen Sheer (Code BL-04) + Charcoal Velvet (Code CV-12)',
      siteDetails: 'Villa 14, Palm Avenue',
      designReferences: 'Architectural moodboard Ref #M-88',
      currentOwner: 'Rhea Sen',
      status: 'Completed',
      delay: 'No',
      createdAt: '2026-09-17T11:00:00.000Z',
    },
    {
      id: 'df-2',
      _id: 'df-2',
      code: 'PRJ-102 (Skyline Penthouse)',
      dueDate: '2026-09-28',
      finalDesignStatus: 'Client Review',
      designVersion: 'v1.1',
      designApprovalDate: '',
      pendingDesignDecisions: 'Client deciding between Off-White and Light Greige',
      clientBrief: 'Minimalist Ripplefold drapes with flush ceiling recess',
      approvedProposalQuote: 'Q-2026-118 (₹8,20,000)',
      fabrics: 'Pure Italian Voile (Code IV-01)',
      siteDetails: 'Penthouse B-3401, The Camellias',
      designReferences: 'Modern European drape aesthetic gallery',
      currentOwner: 'Rhea Sen',
      status: 'In Progress',
      delay: 'No',
      createdAt: '2026-09-22T09:30:00.000Z',
    },
  ],

  executionDrawingRequest: [
    {
      id: 'edr-1',
      _id: 'edr-1',
      code: 'PRJ-101 (Villa Vista)',
      dueDate: '2026-09-22',
      requestDate: '2026-09-20',
      requestedBy: 'DCM Studio Team',
      drawingRequiredByDate: '2026-09-24',
      inputCompletenessStatus: 'Complete',
      drawingVersion: 'v1.0',
      preparedBy: 'Karan Patel',
      checkedBy: 'Sanjay Rao',
      drawingDueDate: '2026-09-24',
      siteDetailSheet: 'Detailed laser measure sheet verified on site',
      pptDesignBrief: 'Villa Vista Drapery Specs PPT v2.0',
      roomWindowReference: 'Living Bay (3 panels), Master Bed (2 panels)',
      measurements: 'Span 4200mm x Drop 3180mm',
      readyHeightStatus: 'Ready',
      pelmetMotorChannelDetails: 'Somfy Glydea Ultra 60 RTS left side housing',
      currentOwner: 'Karan Patel',
      status: 'Completed',
      delay: 'No',
      createdAt: '2026-09-20T10:00:00.000Z',
    },
    {
      id: 'edr-2',
      _id: 'edr-2',
      code: 'PRJ-102 (Skyline Penthouse)',
      dueDate: '2026-09-29',
      requestDate: '2026-09-25',
      requestedBy: 'Ananya Sharma',
      drawingRequiredByDate: '2026-10-02',
      inputCompletenessStatus: 'In Progress',
      drawingVersion: 'v1.0',
      preparedBy: 'Karan Patel',
      checkedBy: 'Sanjay Rao',
      drawingDueDate: '2026-10-02',
      siteDetailSheet: 'Camellias False Ceiling Pelmet Section Attached',
      pptDesignBrief: 'Skyline Penthouse Presentation Deck v1.1',
      roomWindowReference: 'Penthouse Balcony Window 1, 2, 3',
      measurements: 'Span 5800mm x Drop 3400mm',
      readyHeightStatus: 'Pending',
      pelmetMotorChannelDetails: 'Tuya Zigbee Motor with Dual Track Recess',
      currentOwner: 'Karan Patel',
      status: 'In Progress',
      delay: 'No',
      createdAt: '2026-09-25T11:00:00.000Z',
    },
  ],

  executionDrawingPreparation: [
    {
      id: 'edp-1',
      _id: 'edp-1',
      code: 'PRJ-101 (Villa Vista)',
      dueDate: '2026-09-24',
      structuredRequest: 'Elevation & pocket detail for 4 motorized tracks',
      designBrief: 'Wave curtain track recess 160mm x 150mm deep',
      siteDetail: 'Laser measured ceiling height: 3200mm floor-to-ceiling',
      sizes: 'Living: 4200 x 3180mm; Master Bed: 3600 x 3180mm',
      pelmetChannelMotorDetails: 'Somfy Glydea Ultra 60 RTS with left-hand motor housing',
      technicalFeasibilityInput: 'Approved by structural checker. Ceiling load capacity verified.',
      currentOwner: 'Karan Patel',
      status: 'Completed',
      delay: 'No',
      createdAt: '2026-09-21T12:00:00.000Z',
    },
  ],

  approvals: [
    {
      id: 'app-1',
      _id: 'app-1',
      code: 'PRJ-101 (Villa Vista)',
      dueDate: '2026-09-25',
      approvedBy: 'Mr. Rajiv Singhania (Client)',
      approvalDate: '2026-09-25',
      status: 'Approved',
      revisionReason: 'All drawings and finishes accepted without revision',
      approvedDesign: 'v2.0 Approved',
      executionDrawingStatus: 'Approved',
      orderSheet: 'OS-2026-088',
      siteDetails: 'Villa 14, Palm Avenue, Sector 54, Gurgaon',
      measurementStatus: 'Approved',
      customSamplingNeeds: 'Fabric memo sample physically signed by client',
      currentOwner: 'Vikram Mehta',
      delay: 'No',
      createdAt: '2026-09-24T15:00:00.000Z',
    },
    {
      id: 'app-2',
      _id: 'app-2',
      code: 'PRJ-102 (Skyline Penthouse)',
      dueDate: '2026-10-02',
      approvedBy: 'Architect Rahul Kapur',
      approvalDate: '',
      status: 'In Review',
      revisionReason: 'Checking motor pocket tolerance with civil team',
      approvedDesign: 'v1.1 Under Review',
      executionDrawingStatus: 'In Progress',
      orderSheet: 'OS-2026-095 (Draft)',
      siteDetails: 'Penthouse B-3401, The Camellias',
      measurementStatus: 'Incomplete',
      customSamplingNeeds: 'Awaiting 2 swatch cuts from European mill',
      currentOwner: 'Ananya Sharma',
      delay: 'No',
      createdAt: '2026-09-26T10:00:00.000Z',
    },
  ],

  changeRevisionControl: [
    {
      id: 'crc-1',
      _id: 'crc-1',
      code: 'PRJ-101 (Villa Vista)',
      changeRequested: 'Track Profile Finish',
      changeDetails: 'Changed motorized track extrusion finish from Powder White to Anodized Anthracite Gray to match window mullions.',
      costImpact: '₹4,500 (Covered in margin)',
      timelineImpact: '+0 Days (In-stock extrusion used)',
      approvalStatus: 'Approved',
      revisedVersion: 'v2.1',
      currentOwner: 'Vikram Mehta',
      status: 'Completed',
      delay: 'No',
      createdAt: '2026-09-25T16:00:00.000Z',
    },
  ],

  orderSheetFmsCreation: [
    {
      id: 'os-1',
      _id: 'os-1',
      code: 'PRJ-101 (Villa Vista)',
      dueDate: '2026-09-27',
      orderSheetFmsNo: 'OS/FMS-2026-088',
      versionCreatedBy: 'v2.0, Vikram Mehta',
      creationDate: '2026-09-26',
      productionReleaseStatusDate: 'Released to Production on 2026-09-26',
      approvedOrder: 'Approved by DCM & Client',
      roomDetails: 'Living Room: 1x Sheer Wave + 1x Blackout; Master: 1x Motorized Drapes (Fabric & Motor auto-synced)',
      design: 'Ripplefold 120% Fullness Flush Ceiling Recess',
      fabric: '85m Belgian Linen Sheer (Code BL-04) + 110m Velvet Drapes (CV-12)',
      motorAccessoryNeeds: '4x Somfy Glydea Ultra 60 RTS + 2x Telis 4 RTS Remotes',
      stageDates: 'Cut: 2026-09-27 | Stitch: 2026-09-29 | QC: 2026-09-30',
      currentOwner: 'Factory Supervisor',
      status: 'In Production',
      delay: 'No',
      createdAt: '2026-09-26T09:00:00.000Z',
    },
  ],

  procurementRequest: [
    {
      id: 'pr-1',
      _id: 'pr-1',
      code: 'PRJ-101 (Villa Vista)',
      dueDate: '2026-09-28',
      approvedOrderSheet: 'OS/FMS-2026-088',
      procurementStatus: 'Ordered',
      materialReadiness: 'Ready in Warehouse',
      expectedMaterialDate: '2026-09-29',
      procurementDelayException: 'None',
      paymentApprovalIfNeeded: 'Approved by Finance',
      fabricMaterialList: 'BL-04 Sheer Fabric 85m, Somfy Glydea Motors 4 pcs, Heavy Duty Carriers',
      currentOwner: 'Procurement Lead',
      status: 'Completed',
      delay: 'No',
      createdAt: '2026-09-26T10:30:00.000Z',
    },
    {
      id: 'pr-2',
      _id: 'pr-2',
      code: 'PRJ-102 (Skyline Penthouse)',
      dueDate: '2026-10-04',
      approvedOrderSheet: 'OS/FMS-2026-095',
      procurementStatus: 'Draft',
      materialReadiness: 'Pending Supplier Confirmation',
      expectedMaterialDate: '2026-10-08',
      procurementDelayException: 'Fabric mill holiday in Italy',
      paymentApprovalIfNeeded: 'Pending Advance Clearance',
      fabricMaterialList: 'Italian Voile 140m, Tuya Zigbee Motors 6 pcs',
      currentOwner: 'Procurement Lead',
      status: 'In Progress',
      delay: 'Yes',
      createdAt: '2026-09-26T11:00:00.000Z',
    },
  ],

  motorsAccessoriesControl: [
    {
      id: 'mac-1',
      _id: 'mac-1',
      code: 'PRJ-101 (Villa Vista)',
      dueDate: '2026-09-28',
      requirement: '4x Somfy Glydea Ultra 60 RTS with center opening carriers',
      status: 'Completed',
      expectedReadinessDate: '2026-09-28',
      motorType: 'Somfy Glydea Ultra 60 RTS (AC 230V)',
      automationWiringDetails: 'Left-hand power drop with 230V 6A socket above pelmet',
      siteRoomRequirement: 'Living Room (2x tracks 4.2m), Master Bed (2x tracks 3.6m)',
      vendorOrder: 'PO-SOMFY-2026-081',
      accessoriesList: '2x Telis 4 RTS Remotes, 8x Ceiling Brackets, Heavy-duty Belt Drivers',
      currentOwner: 'QC Testing Bench',
      delay: 'No',
      createdAt: '2026-09-27T14:00:00.000Z',
    },
  ],

  qcStatus: [
    {
      id: 'qc-1',
      _id: 'qc-1',
      code: 'PRJ-101 (Villa Vista)',
      dueDate: '2026-09-29',
      qcDoneDate: '2026-09-29',
      qcDoneBy: 'Amit Verma (Chief QC)',
      qcStatus: 'Passed',
      currentOwner: 'Amit Verma',
      delay: 'No',
      status: 'Completed',
      createdAt: '2026-09-29T16:00:00.000Z',
    },
  ],

  packingDispatchReadiness: [
    {
      id: 'pdr-1',
      _id: 'pdr-1',
      code: 'PRJ-101 (Villa Vista)',
      dueDate: '2026-09-30',
      packingStatus: 'Completed',
      dispatchReadinessStatus: 'Ready for Dispatch',
      targetDispatchDate: '2026-10-01',
      installationDate: '2026-10-02',
      packingList: 'Box 1: Living Sheers, Box 2: Master Drapes, Crate 1: Track Extrusions',
      accessories: '4x Motors, 2x Remotes, 16x Fixing Screws & Anchors',
      challan: 'DC-2026-088',
      roomWiseScope: 'Living Room (2 sets), Master Bedroom (2 sets)',
      currentOwner: 'Dispatch Supervisor',
      status: 'Completed',
      delay: 'No',
      createdAt: '2026-09-30T17:00:00.000Z',
    },
  ],

  finalPayment: [
    {
      id: 'fp-1',
      _id: 'fp-1',
      code: 'PRJ-101 (Villa Vista)',
      dueDate: '2026-10-01',
      invoicePaymentSummary: 'INV-2026-114 (Total: ₹4,50,000, Paid: ₹4,50,000)',
      paymentStatus: 'Cleared',
      paymentClearanceDate: '2026-10-01',
      outstandingAmount: '₹0 (100% Cleared)',
      clientStatus: 'Payment Settled',
      dispatchReadiness: 'Ready & Approved for Dispatch',
      currentOwner: 'Finance Team',
      status: 'Completed',
      delay: 'No',
      createdAt: '2026-10-01T11:00:00.000Z',
    },
  ],

  installationScheduling: [
    {
      id: 'is-1',
      _id: 'is-1',
      code: 'PRJ-101 (Villa Vista)',
      dueDate: '2026-10-02',
      confirmedInstallationDateTime: '2026-10-02 at 10:00 AM',
      assignedInstallerTeam: 'Team A (Master Fitters - Lead: Ramesh Kumar)',
      clientConfirmationStatus: 'Confirmed by Client',
      finalPaymentStatus: 'Cleared',
      qcStatus: 'Passed',
      packingStatus: 'Completed',
      siteReadiness: 'Ready & Verified',
      challan: 'DC-2026-088',
      roomWiseScope: 'Living Room (2 sets), Master Bed (2 sets)',
      installerAvailability: 'Confirmed Available',
      currentOwner: 'Installation Lead',
      status: 'Completed',
      delay: 'No',
      createdAt: '2026-09-28T10:00:00.000Z',
    },
  ],

  installationBriefDispatch: [
    {
      id: 'ibd-1',
      _id: 'ibd-1',
      code: 'PRJ-101 (Villa Vista)',
      dueDate: '2026-10-01',
      dispatchDateTime: '2026-10-02 08:30 AM',
      materialHandedOverToReceivedByInstaller: 'Handed Over to Ramesh Kumar (Lead Installer)',
      installationBriefAcknowledged: 'Acknowledged & Signed',
      packingList: '4 Drapery Bundles + 2 Track Crates + Hardware Kit',
      challan: 'DC-2026-088',
      roomScopeList: 'Living Room: 2 Motorized Tracks; Master Suite: 2 Motorized Tracks',
      siteDetails: 'Villa 14, Palm Avenue, Sector 54, Gurgaon',
      clientSiteContact: 'Mr. Rajiv Singhania (+91 98100 XXXXX)',
      motorWiringInfo: 'AC 230V sockets located in top left pocket of pelmet',
      currentOwner: 'Installation Coordinator',
      status: 'Completed',
      delay: 'No',
      createdAt: '2026-10-01T15:00:00.000Z',
    },
  ],

  installationExecutionUpdates: [
    {
      id: 'ieu-1',
      _id: 'ieu-1',
      code: 'PRJ-101 (Villa Vista)',
      dueDate: '2026-10-02',
      installationStartDate: '2026-10-02',
      siteIssueBlocker: 'None - Smooth installation',
      installationPhotosProof: 'All 4 tracks leveled and drapes hung, photos uploaded to project drive',
      installationBrief: 'Brief v2.0 followed; limits set via Somfy Telis remote',
      siteReadiness: 'Site 100% ready, power active',
      material: 'All draperies, tracks, and motors received intact',
      tools: 'Laser level, hammer drill, Somfy limit setting tool',
      siteAccess: 'Service elevator access approved by building estate',
      currentOwner: 'Ramesh Kumar',
      status: 'Completed',
      delay: 'No',
      createdAt: '2026-10-02T15:30:00.000Z',
    },
  ],

  clientExecutionUpdates: [
    {
      id: 'ceu-1',
      _id: 'ceu-1',
      code: 'PRJ-101 (Villa Vista)',
      dueDate: '2026-10-02',
      lastClientUpdateDate: '2026-10-02',
      updatedBy: 'Vikram Mehta',
      nextUpdateDueDate: '2026-10-05',
      projectStage: 'Installation & Handover',
      productionStatus: 'Completed',
      expectedDates: 'Handover on 2026-10-02',
      delays: 'No delays reported',
      installationStatus: 'Completed & Signed',
      clientQueries: 'Client asked about Somfy remote battery change procedure; demonstrated on-site',
      currentOwner: 'Vikram Mehta',
      status: 'Acknowledged',
      delay: 'No',
      createdAt: '2026-10-02T17:00:00.000Z',
    },
  ],

  snagRework: [
    {
      id: 'sr-1',
      _id: 'sr-1',
      code: 'PRJ-101 (Villa Vista)',
      dueDate: '2026-10-03',
      snagId: 'SNAG-2026-088',
      snagOwner: 'Ramesh Kumar',
      targetClosureDate: '2026-10-04',
      snagStatus: 'Closed',
      issueReport: 'Slight wave ripple spacing variance on far right edge',
      closureDate: '2026-10-03',
      closureProof: 'Carrier adjusted to exact 60mm wave pitch, photo approved',
      siteItem: 'Living Room Wave Sheer - Right Edge',
      photosVideo: 'Proof photo uploaded',
      clientComplaint: 'Minor wave alignment observation during handover walkthrough',
      returnedMaterial: 'None required',
      requiredCorrection: 'Adjust end carrier stop position',
      currentOwner: 'Ramesh Kumar',
      status: 'Completed',
      delay: 'No',
      createdAt: '2026-10-03T12:00:00.000Z',
    },
  ],

  maintenance: [
    {
      id: 'mt-1',
      _id: 'mt-1',
      code: 'PRJ-101 (Villa Vista)',
      dueDate: '2026-10-04',
      ticketId: 'TKT-2026-088',
      requestDate: '2026-10-04',
      warrantyStatus: 'Active (5-Year Somfy & Fabric Warranty)',
      owner: 'Support Desk Lead',
      targetResolutionDate: '2027-04-01',
      status: 'Active / Handover Complete',
      closureDate: '2026-10-04',
      clientComplaint: 'No complaints; regular 6-month preventive AMC scheduled',
      siteDetails: 'Villa 14, Palm Avenue, Sector 54, Gurgaon',
      issuePhotos: 'None',
      warrantyMaintenanceContext: 'Standard 5-year mechanical & 2-year stitching coverage',
      priorInstallationRecord: 'Installed & commissioned flawlessly on site',
      currentOwner: 'Support Desk Lead',
      delay: 'No',
      createdAt: '2026-10-04T10:00:00.000Z',
    },
  ],

  projectClosure: [
    {
      id: 'pc-1',
      _id: 'pc-1',
      code: 'PRJ-101 (Villa Vista)',
      dueDate: '2026-10-04',
      projectClosureDate: '2026-10-04',
      approvedBy: 'Mr. Rajiv Singhania (Client)',
      installationCompletion: 'Completed',
      clientSignOff: 'Signed',
      snagStatus: 'Closed',
      paymentClosure: 'Closed',
      challans: 'DC-2026-088 Signed',
      finalPhotos: 'Full site walkthrough photos and 4K video archived in cloud',
      currentOwner: 'Vikram Mehta',
      status: 'Closed',
      delay: 'No',
      createdAt: '2026-10-04T16:00:00.000Z',
    },
  ],
};
